UI/SargeStore/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SargeStore.Interfaces.Services;
using SargeStoreDomain.ViewModels;

namespace SargeStore.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService _CartService;

        public CartController(ICartService CartService) => _CartService = CartService;

        public IActionResult Details() => 
            View(new DetailsViewModel 
            { 
                CartViewModel = _CartService.TransformFromCart(),
                OrderViewModel = new OrderViewModel()
            });

        public IActionResult AddToCart(int id)
        {
            _CartService.AddToCart(id);
            return RedirectToAction("Details");
        }
        public IActionResult DecrementFromCart(int id)
        {
            _CartService.DecrementFromCart(id);
            return RedirectToAction("Details");
        }
        public IActionResult RemoveFromCart(int id)
        {
            _CartService.RemoveFromCart(id);
            return RedirectToAction("Details");
        }
        public IActionResult RemoveAll()
        {
            _CartService.RemoveAll();
            return RedirectToAction("Details");
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult CheckOut(OrderViewModel Model, [FromServices] IOrderService OrderService)
        {
            if (!ModelState.IsValid)
                return View(nameof(Details), new DetailsViewModel
                {
                    CartViewModel =_CartService.TransformFromCart(),
                    OrderViewModel = Model
                });
            var order = OrderService.CreateOrder(Model, _CartService.TransformFromCart(), User.Identity.Name);

            _CartService.RemoveAll();
            return RedirectToAction("OrderConfirmed", new { id = order.Id });
        }

        public IActionResult OrderConfirmed(int id)
        {
            ViewBag.OrderId = id;
            return View();
        }
    }
}

UI/SargeStore/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SargeStore.Interfaces.Services;
using SargeStoreDomain.ViewModels;
using System.Linq;

namespace SargeStore.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        public IActionResult Index() => View();
        public IActionResult Orders([FromServices] IOrderService OrderService)
        {

            return View(OrderService
                .GetUserOrders(User.Identity.Name)
                .Select(order => new UserOrderViewModel
                { 
                    Id = order.Id,
                    Name = order.Name, 
                    Address = order.Address,
                    Phone = order.Phone,
                    TotalSum = order.OrderItems.Sum(item => item.Price * item.Quantity)
                }));
        }
    }
}

UI/SargeStore/Views/Shared/Components/UserInfo/Default.cshtml
<div class="shop-menu pull-right">
    <ul class="nav navbar">
        <li><a asp-controller="Account" asp-action="Login"><i class="fa fa-lock"></i>Вход</a></li>
        <li><a asp-controller="Account" asp-action="Register"><i class="fa fa-user"></i>Регистрация</a></li>
    </ul>
</div>

UI/SargeStore/Views/Shared/Components/UserInfo/UserInfoView.cshtml
@using SargeStoreDomain.Entities.Identity
<div class="shop-menu pull-right">
    <ul class="nav navbar">
        <li><a asp-controller="Profile" asp-action="Index"><i class="fa fa-user"></i>@User.Identity.Name</a></li>
        @if (User.IsInRole(Role.Administrator))
        {
            <li><a asp-area="Admin" asp-controller="Home" asp-action="Index"><i class="fa fa-key"></i>Админка</a></li>
        }

        <li><a href="#"><i class="fa fa-star"></i>Список желаний</a></li>
        <li><a href="#"><i class="fa fa-crosshairs"></i>Заказы</a></li>
        <li><a asp-controller="Cart" asp-action="Details"><i class="fa fa-shopping-cart"></i>Корзина</a></li>

        <li>
            <form asp-controller="Account" asp-action="Logout" asp-antiforgery="true" method="post">
                <button type="submit"><i class="btn btn-link"></i>Выход</button>
            </form>
        </li>

    </ul>
</div>